# Generated by Django 6.0.3 on 2026-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('workout', models.CharField(blank=True, max_length=200, null=True)),
                ('diet', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
